# 数据库配置信息
jdbc.driver=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://47.106.225.251:3306/web
jdbc.username=root
jdbc.password=uniontech3d.cn%1234
#连接
initSize=50
maxSize=300


#mongodb 配置
mongo.ip=10.10.12.17
mongo.port=27017
mongo.username=spider
mongo.password=spider
mongo.dbname=spider